@extends('layouts.app')
@section('content')
<div class="top"><div><div class="eyebrow">Finance / Billing</div><div class="h1">Invoices & Recharge</div><div class="sub">Issue invoices, record payments, and manage client balances by currency.</div></div><span class="pill">Multi-currency ledger</span></div>
@if(session('notice'))<div class="notice">{{ session('notice') }}</div>@endif
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<div class="split">
<section class="card"><h2>Create invoice</h2><form method="POST" action="{{ route('admin.invoices.store') }}">@csrf<div class="formgrid"><label>Client<select name="customer_id" required><option value="">Select client</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} ({{ $customer->currency }})</option>@endforeach</select></label><label>Currency<select name="currency" required>@foreach($currencies as $currency)<option value="{{ $currency->code }}">{{ $currency->code }} — {{ $currency->name }}</option>@endforeach</select></label><label>Due date<input type="date" name="due_date"></label><label>Description<input name="description" placeholder="SMS traffic / recharge" required></label><label>Quantity<input type="number" name="quantity" min="0.000001" step="0.000001" value="1" required></label><label>Unit price<input type="number" name="unit_price" min="0" step="0.000001" placeholder="0.000000" required></label><label>Tax<input type="number" name="tax" min="0" step="0.000001" value="0"></label></div><label style="margin-bottom:14px">Notes<textarea name="notes" rows="2" style="background:#fff;color:var(--text);border:1px solid #cbd9e4;border-radius:6px;padding:10px"></textarea></label><button class="button" type="submit">Issue invoice</button></form></section>
<section class="card"><h2>Client balances</h2>@forelse($customers as $customer)<div class="row"><span><strong>{{ $customer->name }}</strong><small style="display:block;color:var(--muted)">{{ $customer->email }}</small></span><span class="tag">{{ number_format((float)$customer->balance, 4) }} {{ $customer->currency }}</span></div>@empty<div class="sub">No customer accounts found.</div>@endforelse</section>
</div>
<section class="card" style="margin-top:15px"><div class="top"><h2 style="margin:0">Invoice register</h2><span class="status">{{ $invoices->count() }} records</span></div><div class="tablewrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Issue / Due</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th>Payment</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><strong>{{ $invoice->invoice_number }}</strong><br><small>{{ $invoice->currency }}</small></td><td>{{ $invoice->customer_name }}<br><small>{{ $invoice->email }}</small></td><td>{{ $invoice->issue_date }}<br><small>{{ $invoice->due_date ?: 'No due date' }}</small></td><td>{{ number_format((float)$invoice->total, 4) }} {{ $invoice->currency }}</td><td>{{ number_format((float)$invoice->paid, 4) }}</td><td>{{ number_format(max(0, (float)$invoice->total - (float)$invoice->paid), 4) }}</td><td><span class="tag">{{ $invoice->status }}</span></td><td><details><summary class="button">Post payment</summary><form method="POST" action="{{ route('admin.invoices.payment', $invoice->id) }}" style="min-width:340px;padding:12px">@csrf<label>Amount<input type="number" name="amount" min="0.000001" step="0.000001" max="{{ max(0, (float)$invoice->total - (float)$invoice->paid) }}" required></label><label>Reference<input name="reference" placeholder="BANK-TRX-001" required></label><label>Method<select name="method"><option value="BANK">Bank</option><option value="CARD">Card</option><option value="CASH">Cash</option><option value="MANUAL">Manual</option></select></label><button class="button" style="margin-top:10px" type="submit">Post</button></form></details></td></tr>@empty<tr><td colspan="8">No invoices created yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
