@extends('layouts.app')
@section('content')
<div class="top"><div><div class="eyebrow">Operations / Monitoring</div><div class="h1">SMPP Monitor</div><div class="sub">Customer binds, provider health, client activity and gateway logs.</div></div><div><span class="pill">{{ $jasminOnline ? '● Jasmin HTTP ONLINE' : '● Jasmin OFFLINE' }}</span> <a class="button" href="{{ route('admin.monitoring') }}">Refresh</a></div></div>
<div class="grid"><div class="card"><div class="label">Jasmin HTTP API</div><div class="value {{ $jasminOnline ? 'good' : 'bad' }}">{{ $jasminOnline ? 'ONLINE' : 'OFFLINE' }}</div></div><div class="card"><div class="label">SMPP accounts</div><div class="value">{{ $smppUsers->count() }}</div></div><div class="card"><div class="label">Providers</div><div class="value">{{ $providers->count() }}</div></div><div class="card"><div class="label">Client records</div><div class="value">{{ $clientActivity->count() }}</div></div></div>
<section class="card" style="margin-top:15px"><h2>Customer SMPP user status</h2><div class="sub" style="margin-bottom:12px">Account enabled state is shown here; live bind events are read from Jasmin log files mounted into the Laravel container.</div><div class="tablewrap"><table><thead><tr><th>User</th><th>System ID</th><th>Max bind</th><th>TPS</th><th>Enabled</th><th>Observed status</th></tr></thead><tbody>@forelse($smppUsers as $user)<tr><td>{{ $user->name }}<br><small>{{ $user->email }}</small></td><td>{{ $user->system_id }}</td><td>{{ $user->max_bind }}</td><td>{{ $user->tps }}</td><td><span class="tag">{{ $user->enabled ? 'ENABLED' : 'DISABLED' }}</span></td><td><span class="tag">{{ $user->enabled ? 'READY / CHECK LOG' : 'BLOCKED' }}</span></td></tr>@empty<tr><td colspan="6">No customer SMPP accounts configured yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="card" style="margin-top:15px"><h2>Provider connection status</h2><div class="tablewrap"><table><thead><tr><th>Provider</th><th>Host</th><th>Port</th><th>Status</th><th>Last health</th><th>Priority</th></tr></thead><tbody>@forelse($providers as $provider)<tr><td>{{ $provider->name }}</td><td>{{ $provider->host }}</td><td>{{ $provider->port }}</td><td><span class="tag">{{ $provider->status }}</span></td><td>{{ $provider->last_health_at ?? 'Not checked' }}</td><td>{{ $provider->priority }}</td></tr>@empty<tr><td colspan="6">No providers configured yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="card" style="margin-top:15px"><h2>Client SMS activity</h2><div class="tablewrap"><table><thead><tr><th>Created</th><th>Message ID</th><th>Source</th><th>Destination</th><th>Status</th><th>Charge</th></tr></thead><tbody>@forelse($clientActivity as $item)<tr><td>{{ $item->created_at }}</td><td><code>{{ \Illuminate\Support\Str::limit($item->message_id, 14) }}</code></td><td>{{ $item->source }}</td><td>{{ $item->destination }}</td><td><span class="tag">{{ $item->final_status }}</span></td><td>{{ number_format($item->customer_charge, 4) }}</td></tr>@empty<tr><td colspan="6">No client SMS activity yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="card" style="margin-top:15px"><h2>Server / Jasmin logs</h2><div class="loggrid">@forelse($logs as $name => $lines)<div><h3>{{ $name }}</h3><pre>@foreach($lines as $line){{ $line }}
@endforeach</pre></div>@empty<div class="sub">No mounted Jasmin log files found yet. Use `docker compose logs jasmin` for container stdout.</div>@endforelse</div></section>
@endsection
